### ISSUE TITLE
Error: Polygon Division Failed: Output Dataset Invalid by use for multipart polygon

### ISSUE THREAD

**Issue by IlseMeijer** [jonnyhuck/RFCL-PolygonDivider#16]
Thank you for this great plugin, it works great for me on single part polygons.
But it gave an error message when I tried to divide the following multipart polygon into 20 equal parts,  

![afbeelding](https://user-images.githubusercontent.com/55970446/138886647-9694039c-aa87-4c33-8d93-3b49a3cb5879.png)

As a result I got the error message: Polygon Division Failed: Output Dataset Invalid. 
Isn't it possible to use Polygon Divider for a multipart polygon? Does someone know how to fix this?

I would really appreciate any help with using Polygon Divider for multipart polygons.

The multipart polygon shape can be found in this file:
[MultipartPolygon.zip](https://github.com/jonnyhuck/RFCL-PolygonDivider/files/7418581/MultipartPolygon.zip)

**Comment by jonnyhuck** [comment]
Thanks for this - it should work fine with MultiPolygons as far as I know - I am afraid that your zip only includes the .qlr file (which seems to point to a PostGIS database) - could you please dataset as a Shapefile, GeoPackage or similar  and I'll take a look?

**Comment by IlseMeijer** [comment]
Thank you for your quick response and my apologies that I didn't include a correct shapefile. I hope that I did it correctly this time.

[BkkRE99c.zip](https://github.com/jonnyhuck/RFCL-PolygonDivider/files/7434014/BkkRE99c.zip)

**Comment by jonnyhuck** [comment]
OK, the issue here is that the dataset is not projected, which is causing a mathematical error - it divides fine if you project it first (in this case to UTM zone 32N - EPSG:32632):

![image](https://user-images.githubusercontent.com/8895744/139442854-80aa498c-3a1d-4d94-9413-3cd68b04ac34.png)

Sorry about that - I clearly need to do some work to catch errors like this (and figure out exactly where the issue is)! For now, if you need it in WGS84 (EPSG:4326) then you could always de-project it again afterwards by right clicking on it in the layer list, then selecting Export and setting the CRS. In general, I would recommends using this on projected datasets only, as the underlying maths assumes that the are working on a flat surface (as opposed to a sphere or ellipsoid).

Thanks for pointing it out! I'll try and find some time to put in a workaround (or at least a more helpful error message!).

**Comment by IlseMeijer** [comment]
Many thanks again for your quick reply and your solution/workarond for this problem.

I do have an additonial question: I can only divide one (mulit)polygon at the time? I have a shape-file with in total 192 (multi)polygons and I want to divide each separate (multi)polygon into 20 equal parts. When more polygons are selected, the total area of the polygons is divided into 20 parts instead of each polygon into 20 parts.

**Comment by jonnyhuck** [comment]
This is a good question - unfortunately this isn't possible at the moment. 

There are a couple of solutions that could fix this: one being to build this as an option into the existing plugin; and the other being to integrate the plugin into the Processing Toolbox (which you could then use to run 'batch' jobs within QGIS). 

I would be very happy to take these as feature requests, but I don't think that I would have time to get either done in the near future (though I am very happy to receive pull requests if anyone out there wants to give it a go).

**Comment by JianbiaoW30** [comment]
Thank you for this nice plugin! It simplify my work significantly.

I have the same problem that I want to apply this plugin to each polygon in the shape file, and there are more than 200 polygons in this file. I was trying to integrate the plugin into the processing toolbox, but I cannot find any instructions. 

If possible, could you kindly tell me how to integrate it?

**Comment by IlseMeijer** [comment]
Again my apologies to Jonny that I haven't replied to his latest answer sooner!

I am not so proficient with QGis that I could get this plugin working with his suggestions.
I found a way around by using other software provided to me by my employer.

**Comment by jonnyhuck** [comment]
Yes - there are two choices really - one is to edit the plugin so that it has ther option to divide each feature in a dataset separately; and the other is to re-write the pluggin to be a 'Processing plugin', which would enable it to be run in batch mode (this requires re-writing the code for part of the plugin) - for the latter you would have to 'explode' the shapefile into multiple files though I think (there is a tool for this in QGIS). 

I have no objection to doing this (the first idea is maybe the best one) - but it will take a little time as I am a bit snowed under at the moment. Very happy for a PR is anyone has the time in the meantime though.
